### ISSUE TITLE
What to do with the links and post deleted by author.

### ISSUE THREAD

**Issue by Lorhelei** [jacklul/e621-Batch-Reverse-Search#9]
This is mostly a question, what can I do know with the links? And is there a way to filter those that were deleted by the author?

I think this app has so much potential, yet I'm practically stuck with a bunch of links that I can't find the way to bulk download them on their original sizes.

Maybe is there something I'm missing?

**Comment by jacklul** [comment]
The general idea was to make reverse search easier and faster, script generates HTML file with all links so they are easily clickable, probably can be used with HTTrack to download each page and images.

I do no do checks whenever the linked image was deleted or not - that would only put delays on the search.

Bulk download can be unreliable because sometimes results even if the search engine is 90% sure that picture matches they end up being totally different, it's best to download manually and even some prefer going to source page instead of downloading from e621.

**Comment by Lorhelei** [comment]
I see. The only problem I see with that is that when using only the names of the file, I had to check exactly what file was I was looking for since most of the filenames were md5 or just random numbers.

Since it's a html file, couln't link the actual file and show the image above its link like a thumbnail? I think is possible but it has been a while since I touch anything Web and I don't know if it will be better for the app, hehe. 

Just asking. 

Still I'm impressed of how well the apps goes. Keep up the incredible job.

**Comment by jacklul** [comment]
Checkout new release: https://github.com/jacklul/e621-Batch-Reverse-Search/releases/tag/1.3.0
links.html will have to be deleted to make the hover work

**Comment by Lorhelei** [comment]
Wow, it looks very good. The images are a bit too big in some cases, but they look awesome. Great job!
